import { create } from 'zustand';

interface LanguageState {
  lang: 'zh' | 'en';
  setLang: (lang: 'zh' | 'en') => void;
  t: (key: string) => string;
}

const translations: Record<string, Record<string, string>> = {
  en: {
    top_models: 'Top Models',
    weekly_usage_across_openrouter: 'Weekly usage of models across OpenRouter',
    loading: 'Loading...',
    failed_fetch_top_models: 'Failed to fetch top models data',
    failed_to_load_data: 'Failed to load data',
    hover_to_see_data: 'Hover to see data',
    hover_chart_to_view: 'Hover over chart to view details',
    total: 'Total',
    leaderboard: 'LLM Leaderboard',
    compare_popular_models: 'Compare the most popular models on OpenRouter',
    this_week: 'This Week',
    market_share: 'Market Share',
    compare_token_share: 'Compare OpenRouter token share by model author',
    benchmarks: 'Benchmarks',
    model_performance: 'Model performance across benchmark categories',
    fastest_models: 'Fastest Models',
    highest_output_speed: 'Models with highest output speed',
    categories: 'Categories',
    categories_desc: 'Popular model categories on OpenRouter',
    languages: 'Languages',
    languages_desc: 'Models supporting natural language input',
    programming: 'Programming',
    programming_desc: 'Models optimized for code generation',
    context_length: 'Context Length',
    requests_by_length: 'Requests by prompt & completion length on OpenRouter',
    tool_calls: 'Tool Calls',
    tool_calls_desc: 'Models that support tool/function calling',
    images: 'Images',
    images_desc: 'Models that support image input',
    image_output: 'Image Output',
    image_output_desc: 'Models that can generate images',
    audio_input: 'Audio Input',
    audio_input_desc: 'Models that support audio input',
    top_apps: 'Top Apps',
    top_applications: 'Top applications using OpenRouter',
    model: 'Model',
    models: 'models',
    math: 'Math',
    coding: 'Coding',
    reasoning: 'Reasoning',
    chat: 'Chat',
    average: 'Average',
    speed: 'Speed',
    tokens_sec: 'tokens/sec',
    context: 'Context',
    input_price: 'Input Price',
    output_price: 'Output Price',
    capabilities: 'Capabilities',
    description: 'Description',
    provider: 'Provider',
    search_placeholder: 'Search models...',
    filter_by_category: 'Filter by category',
    context_length_filter: 'Context Length',
    all: 'All',
    one_k_to_ten_k: '1K - 10K',
    ten_k_to_hundred_k: '10K - 100K',
    hundred_k_plus: '100K+',
    back: 'Back',
    model_details: 'Model Details',
    max_completion_tokens: 'Max Completion Tokens',
    supported_parameters: 'Supported Parameters',
    weekly_tokens: 'Weekly Tokens',
    weekly_change: 'Weekly Change',
    rank: 'Rank',
    token_usage: 'Token Usage',
    change: 'Change',
    view_details: 'View Details',
    tokens: 'tokens',
    show_more: 'Show more',
    show_less: 'Show less',
    hero_subtitle: 'Based on benchmarks and real usage data from millions of users accessing models through OpenRouter.',
    powered_by: 'Powered by',
    modality: 'Modality',
    input_modalities: 'Input Modalities',
    output_modalities: 'Output Modalities',
    navigation: 'Navigation',
  },
  zh: {
    top_models: '顶级模型',
    weekly_usage_across_openrouter: 'OpenRouter 上模型的周使用量',
    loading: '加载中...',
    failed_fetch_top_models: '获取顶级模型数据失败',
    failed_to_load_data: '加载数据失败',
    hover_to_see_data: '悬停查看数据',
    hover_chart_to_view: '悬停图表查看详情',
    total: '总计',
    leaderboard: 'LLM 排行榜',
    compare_popular_models: '比较 OpenRouter 上最受欢迎的模型',
    this_week: '本周',
    market_share: '市场份额',
    compare_token_share: '按模型作者比较 OpenRouter token 份额',
    benchmarks: '基准测试',
    model_performance: '模型在基准测试类别中的表现',
    fastest_models: '最快模型',
    highest_output_speed: '输出速度最快的模型',
    categories: '分类',
    categories_desc: 'OpenRouter 上热门的模型分类',
    languages: '语言支持',
    languages_desc: '支持自然语言输入的模型',
    programming: '编程',
    programming_desc: '针对代码生成优化的模型',
    context_length: '上下文长度',
    requests_by_length: 'OpenRouter 上按提示词和完成长度统计的请求',
    tool_calls: '工具调用',
    tool_calls_desc: '支持工具/函数调用的模型',
    images: '图像输入',
    images_desc: '支持图像输入的模型',
    image_output: '图像输出',
    image_output_desc: '可以生成图像的模型',
    audio_input: '音频输入',
    audio_input_desc: '支持音频输入的模型',
    top_apps: '热门应用',
    top_applications: '使用 OpenRouter 的热门应用',
    model: '模型',
    models: '个模型',
    math: '数学',
    coding: '编码',
    reasoning: '推理',
    chat: '对话',
    average: '平均',
    speed: '速度',
    tokens_sec: 'tokens/秒',
    context: '上下文',
    input_price: '输入价格',
    output_price: '输出价格',
    capabilities: '能力',
    description: '描述',
    provider: '提供商',
    search_placeholder: '搜索模型...',
    filter_by_category: '按分类筛选',
    context_length_filter: '上下文长度',
    all: '全部',
    one_k_to_ten_k: '1K - 10K',
    ten_k_to_hundred_k: '10K - 100K',
    hundred_k_plus: '100K+',
    back: '返回',
    model_details: '模型详情',
    max_completion_tokens: '最大完成 tokens',
    supported_parameters: '支持的参数',
    weekly_tokens: '周使用量',
    weekly_change: '周变化',
    rank: '排名',
    token_usage: 'Token 使用量',
    change: '变化',
    view_details: '查看详情',
    tokens: 'tokens',
    show_more: '显示更多',
    show_less: '显示更少',
    hero_subtitle: '基于基准测试和数百万用户通过 OpenRouter 访问模型的真实使用数据。',
    powered_by: '由',
    modality: '模态',
    input_modalities: '输入模态',
    output_modalities: '输出模态',
    navigation: '导航',
  },
};

export const useLanguageStore = create<LanguageState>((set, get) => ({
  lang: 'zh',
  setLang: (lang) => set({ lang }),
  t: (key) => translations[get().lang][key] || key,
}));